[package]
name = "kepub"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "kepub"
path = "src/bin/main.rs"

[lib]
name = "kepub"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["std", "derive", "env"] }
epub-builder = "0.8"
html-escape = "0.2"
image = "0.25"
indicatif = "0.18"
lopdf = "0.38"
pdf-extract = "0.10"
quick-xml = "0.38"
regex = "1.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.46", features = ["macros", "rt", "rt-multi-thread", "sync"] }
xml-rs = "0.8"
zip = "4.3"
